USE MuhasebeOtomasyon
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE DBO.TBL_FATURALAR(
ID INT IDENTITY(1,1) NOT NULL,
FATURATURU NVARCHAR(25) NULL,
FATURASERI NVARCHAR(5) NULL,
FATURANO NVARCHAR(15) NULL,
IRSALIYEID INT NULL,
CARIKODU NVARCHAR(30) NULL,
TARIHI DATETIME NULL,
ACIKLAMA TEXT NULL,
GENELTOPLAM DECIMAL(18,2) NULL,
ODEMEYERI NVARCHAR(10) NULL,
ODEMEYERIID INT NULL,
SAVEUSER INT NULL,
SAVEDATE DATETIME NULL,
EDITUSER INT NULL,
EDITDATE DATETIME NULL,

CONSTRAINT PK_TBL_FATURALAR PRIMARY KEY CLUSTERED
(
ID ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS=ON, ALLOW_PAGE_LOCKS= ON) ON [PRIMARY]


) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO