USE MuhasebeOtomasyon
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE DBO.TBL_IRSALIYELER(
ID int IDENTITY(1,1) NOT NULL,
IRSALIYESERI NVARCHAR(5) NULL,
IRSALIYENO NVARCHAR(15) NULL,
FATURAID INT NULL,
CARIKODU NVARCHAR(30) NULL,
TARIHI DATETIME NULL,
ACIKLAMA TEXT NULL,
SAVEUSER INT NULL,
SAVEDATE DATETIME NULL,
EDITUSER INT NULL,
EDITDATE DATETIME NULL,

CONSTRAINT PK_TBL_IRSALIYELER PRIMARY KEY CLUSTERED
(
ID ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
