USE MuhasebeOtomasyon
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE TABLE dbo.TBL_STOKHAREKETLERI(
ID int IDENTITY(1,1) NOT NULL,
FATURAID int NULL,
IRSALIYEID int NULL,
STOKKODU nvarchar(30) NULL,
GCKODU nvarchar(1) NULL,
MIKTAR int NULL,
BIRIMFIYAT decimal(18,2) NULL,
KDV decimal(8,2) NULL,
TIPI nvarchar(20) NULL,
SAVEUSER int NULL,
SAVEDATE datetime NULL,
EDITUSER int NULL,
EDITDATE datetime NULL,

CONSTRAINT PK_TBL_STOKHAREKETLERI PRIMARY KEY CLUSTERED
(
ID ASC
)
WITH (PAD_INDEX=OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]



) ON [PRIMARY]

GO

ALTER TABLE dbo.TBL_STOKHAREKETLERI ADD CONSTRAINT [DF_TBL_STOKHAREKETLERI_SAVEUSER] DEFAULT ((-1)) FOR [SAVEUSER]
GO

ALTER TABLE dbo.TBL_STOKHAREKETLERI ADD CONSTRAINT [DF_TBL_STOKHAREKETLERI_SAVEDATE] DEFAULT (getdate()) FOR [SAVEDATE]
GO

ALTER TABLE dbo.TBL_STOKHAREKETLERI ADD CONSTRAINT [DF_TBL_STOKHAREKETLERI_EDITUSER] DEFAULT ((-1)) FOR [EDITUSER]
GO

ALTER TABLE dbo.TBL_STOKHAREKETLERI ADD CONSTRAINT [DF_TBL_STOKHAREKETLERI_EDITDATE] DEFAULT (getdate()) FOR [EDITDATE]
GO